apiVersion: v2
name: mychart
description: A Helm chart for Helm Integrator
type: application
version: 0.9.0
appVersion: "1.0.0"
dependencies:
- name: postgresql
  version: "13.0.0"
  repository: "https://charts.bitnami.com/bitnami"