appExternalSecret:
  name: app-secret
  refreshInterval: 5m
  env:
    - name: DB_PASSWORD
      value: /postgres/POSTGRES_PASSWORD
    - name: DB_USER
      value: /postgres/POSTGRES_USER
    - name: DB_NAME
      value: /postgres/POSTGRES_DB
    - name: SECRET_KEY
      value: /app/SECRET_KEY
default:
  name: app-default-secret
  image: alex130a/helm-integrator-app:latest
  app_port: 8000
  replicas: 1
  debug: 0
secretStoreCredentials:
  name: aws-creds
  # Specified de Access Key and Access Key ID to connect to aws
  aws_access_key_id: ""
  aws_secret_access_key: ""
ingress:
  enable: true
  host: helm-integrator.com
  ingressClassName: nginx
postgresql:
  auth:
    database: 
    password: 
    username: 