apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-app-service" .Release.Name }}
  labels:
    app: app-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: app
  