apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-app" .Release.Name }}
  labels:
    app: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: {{ .Values.default.replicas | default 1 }}
  template:
    metadata:
      name: {{ printf "%s-app" .Release.Name }}
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: {{ .Values.default.image | quote }}
        envFrom:
          - secretRef:
              name: {{ .Values.appExternalSecret.name }}
          - configMapRef:
              name: app-default-env
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-app-migration" .Release.Name }}
spec:
  template:
    spec:
      containers:
      - name: app
        image: {{ .Values.default.image | quote }}
        command: ["python","manage.py", "migrate"]
        envFrom:
          - secretRef:
              name: {{ .Values.appExternalSecret.name }}
          - configMapRef:
              name: app-default-env
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-default-env
data:
  DB_PORT: "5432"
  APP_PORT: {{ .Values.default.app_port | default 8000 | quote }}
  DEBUG: {{ .Values.default.debug | default 0 | quote }}
  DB_HOST: {{ printf "%s-postgresql-hl" .Release.Name }}
