apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-external-secret
spec:
  refreshInterval: {{ .Values.appExternalSecret.refreshInterval }}
  secretStoreRef:
    name: parameterstore
    kind: SecretStore
  target:
    name: {{ .Values.appExternalSecret.name }}
    creationPolicy: Owner
  data:
    {{- range $item := .Values.appExternalSecret.env }}
    - secretKey: {{ $item.name }}
      remoteRef:
        key: {{ $item.value }}
    {{- end }}