apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStoreCredentials.name }}
            key: aws_access_key_id
          secretAccessKeySecretRef: 
            name: {{ .Values.secretStoreCredentials.name }}
            key: aws_secret_access_key
          # Optional, only if you are using session tokens
          {{- if .Values.secretStoreCredentials.isStsEnable }}
          sessionTokenSecretRef:
            name: {{ .Values.secretStoreCredentials.name }}
            key: aws_session_token
          {{- end }}