{{- if .Values.secretStoreCredentials.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretStoreCredentials.name | default "aws-creds" }}
data:
  aws_secret_access_key: {{ .Values.secretStoreCredentials.aws_secret_access_key | b64enc }}
  aws_access_key_id: {{ .Values.secretStoreCredentials.aws_access_key_id | b64enc }}
{{- end }}