name: Release Charts
on:
  push:
    branches:
      - master
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.3
      - name: Package and Publish Chart
        run: |
          cp -r mychart /tmp/mychart
          git checkout gh-pages
          cp -r /tmp/mychart mychart
          helm package mychart
          helm repo index .

          echo "----Limpiando archivos----"
          rm -rf .github
          rm -rf mychart
          
          GIT_STATUS=$(git status --porcelain)
          
          if [ -n "$GIT_STATUS" ]; then
            echo "----Cambios detectados. Realizando commit y push----"
            git add .
            git commit -m "job number - ${{ github.run_number }}"
            git push
          else
            echo "----No hay cambios----"
          fi
