name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    # Es una buena práctica darle permisos específicos a la acción que los necesita.
    permissions:
      contents: write # para hacer push a gh-pages y crear releases
      packages: write # opcional, si publicas a un registro de paquetes de GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Necesitamos el historial completo para que chart-releaser pueda detectar cambios.
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        # Esta es la acción clave. ¡Hace todo el trabajo pesado!
        uses: helm/chart-releaser-action@v1.6.0
        env:
          # El token es necesario para crear los releases y hacer push a gh-pages
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"