name: Release Charts
on:
  push:
    branches:
      - master
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config usaer.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
          helm version
      - name: Package and Publish Chart
        run: |
          cp -r mychart /tmp/mychart
          git checkout gh-pages
          cp -r /tmp/mychart mychart
          helm package mychart
          helm repo index .
          rm -rf .github
          rm -rf mychart
          GIT_STATUS=$(git status --porcelain) # output in an easy-to-parse format for scripts
          echo $GIT_STATUS
          git add .
          if [ "$GIT_STATUS" != "" ]; then git commit -m "job number - ${{ github.run_number }}"; fi
          if [ "$GIT_STATUS" != "" ]; then git push; fi
